baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "North Brooklyn Angels"
paginate = 10
enableGitInfo = true

# Need to raise this because it times out when building on GitHub
timeout = 300000

# disableKinds = ["RSS",  "sitemap"]

contentDir = "../content"

[permalinks]
    "in-the-news" = "/in-the-news/:year/:month/:slug/"

[taxonomies]
    source = "source"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.tableOfContents]
        startLevel = 1

[imaging]
resampleFilter = "Lanczos"
quality = 80
anchor = "smart"
bgColor = "#ffffff"

[params]
# Meta description
Description = "We're North Brooklyn Angels, a volunteer-powered non-profit in Brooklyn that brings food to where the need is through our mobile soup kitchen (the Angelmobile). We now regularly serves over 3,000 hot, healthy meals a week at six locations in North Brooklyn."
# Meta keywords
Keywords = "soup kitchen, mobile soup kitchen, north brooklyn angels, nba, charity"