name: CI/CD

on:
  push:
    branches: "master"
  pull_request:
    branches: "master"

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: "14"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%G%W")"
      shell: bash

    - name: Cache generated resources
      uses: actions/cache@v2
      id: cache-gen-resources
      with:
        path: |
          site/resources
        key: ${{ runner.os }}-{{ steps.get-date.outputs.date }}

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        git config --global user.name "North Brooklyn Angels"
        git config --global user.email "northbrooklynangels@gmail.com"
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
