name: Deploy

on:
  push:
    branches: "master"
  pull_request:
    branches: "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

      # Should be fine for future Node LTS versions
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "npm"

    - name: Restore generated image assets and dependencies
      uses: actions/cache/restore@v4
      id: cache-restore
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: |
          site/resources
          node_modules
        key: ${{ runner.os }}-cache

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Cache generated image assets and dependencies for later
      uses: actions/cache/save@v4
      id: cache-save
      with: 
        path: |
          site/resources
          node_modules
        key: ${{ runner.os }}-cache

    - name: Deploy with gh-pages
      run: |
        git config --global user.name "North Brooklyn Angels"
        git config --global user.email "northbrooklynangels@gmail.com"
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}