name: Deploy

on:
  push:
    branches: "master"
  pull_request:
    branches: "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

      # Should be fine for future Node LTS versions
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "npm"

    - name: Restore generated image assets
      uses: actions/cache/restore@v4
      id: cached-images-restore
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: site/resources
        key: ${{ runner.os }}-cached-images

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Cache generated image assets for later
      uses: actions/cache/save@v4
      id: cached-images-save
      with: 
        path: site/resources
        key: ${{ runner.os }}-cached-images

    - name: Upload Pages artifacts
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: dist
        retention-days: 1
        if-no-files-found: error
  
  deploy: 
    needs: build

    permissions: 
      pages: write
      id-token: write
    
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4